module.exports = {
  site: {
    title: "P2020 - Software Engineer Website 🧐",
    shortTitle: "P2020",
    description: "Software Engineer Website 🧐",
    keywords: "software, engineer, developer, code, javascript, python",
    url: "https://github.com/halfrice/p2020",
    prefix: "/",
    language: "en_US",
  },
  manifest: {
    name: "P2020",
    shortName: "P2020",
    startUrl: "/",
    backgroundColor: "#101114",
    themeColor: "#202124",
    display: "minimal-ui",
    lang: "en",
  },
  navLinks: [
    {
      name: "About",
      url: "/#about",
    },
    {
      name: "Apps",
      url: "/#apps",
    },
    {
      name: "Contact",
      url: "/#contact",
    },
  ],
  footerLinks: [
    { name: "React", url: "#" },
    { name: "GatsbyJS", url: "#" },
    { name: "Netlify", url: "#" },
  ],
  socialMedia: [
    {
      name: "Facebook",
      url: "https://facebook.com",
      color: "#3b5998",
      username: "Facebook",
    },
    {
      name: "Google",
      url: "mailto:gmail@gmail.com",
      color: "#4285f4",
      username: "Gmail.com",
    },
    {
      name: "Twitter",
      url: "https://twitter.com/",
      color: "#1da1f2",
      username: "Twitter",
    },
    {
      name: "Linkedin",
      url: "https://linkedin.com",
      color: "#405de6",
      username: "Linkedin",
    },
    {
      name: "Github",
      url: "https://github.com/halfrice",
      color: "#4078c0",
      username: "Github",
    },
    {
      name: "Codepen",
      url: "https://codepen.io/halfrice",
      color: "#0ebeff",
      username: "Codepen",
    },
  ],
  scrollrevealConfig: (delay = 200) => ({
    origin: "bottom",
    distance: "4rem",
    rotate: { x: 0, y: 0, z: 0 },
    delay,
    useDelay: "always",
    duration: 500,
    opacity: 0,
    scale: 1,
    easing: "ease-in-out",
    desktop: true,
    mobile: true,
    reset: false,
    viewFactor: 0,
    viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
  }),
}
